name: Build Docker
on:
  workflow_run:
    workflows: [ "Build and Test" ]
    types:
      - completed
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

#  test-docker:
#    needs: build-docker
#    runs-on: ubuntu-latest
#    container:
#      image: mlevental/openhls:latest
#    steps:
#      - name: Check the built docker image
#        run: |
#          cd /openhls
#          export OPENHLS_CONFIG_FP=$(pwd)/openhls_config.ini
#          python examples/simple_nns.py linear --size 11
#          openhls_compiler $(pwd)/examples/linear_11/linear.mlir -t -r -s -v -b -n 10 --threshold 0.1
