name: Build Docker
on:
  workflow_run:
    workflows: [ "Build and Test" ]
    types:
      - completed
    branches: [ main ]
jobs:
  build-docker:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PW }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: mlevental/bragghls:latest
  test-docker:
    needs: build-docker
    runs-on: ubuntu-latest
    container:
      image: mlevental/bragghls:latest
    steps:
      - name: Check the built docker image
        run: |
          cd /bragghls
          export BRAGGHLS_CONFIG_FP=$(pwd)/bragghls_config.ini
          python examples/simple_nns.py linear --size 11
          bragghls_compiler $(pwd)/examples/linear_11/linear.mlir -t -r -s -v -b -n 10 --threshold 0.1
