name: Build and Test
on: [push, pull_request, workflow_dispatch]
jobs:
  build-bragghls:
    strategy:
      fail-fast: true
      matrix:
#        os: [ macos-12, ubuntu-22.04 ]
        os: [ ubuntu-22.04 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Get bragghls
        uses: actions/checkout@v2
        with:
          submodules: 'false'

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install python packages
        run: python -m pip install -r requirements.txt
      
      - name: Install linux system packages
        if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo apt-get install libgmp3-dev libmpfr-dev libmpfi-dev iverilog ninja-build

      - name: Install macos system packages
        if: matrix.os == 'macos-12'
        run: |
          brew install llvm gmp mpfr mpfi icarus-verilog

      - name: Build and Test bragghls
        run: |
          ./scripts/clone_externals.sh
          pip install . -vvvv
          BRAGGHLS_CONFIG_FP=bragghls_config.ini python $(pwd)/examples/linear.py
          BRAGGHLS_CONFIG_FP=$(pwd)/bragghls_config.ini bragghls_compiler $(pwd)/examples/linear_bragghls_artifacts/linear.mlir -t -r -s -v -b
          
          
